using Microsoft.VisualStudio.TestTools.UnitTesting;using PropRiskManager.Domain;
namespace PropRiskManager.Tests;
[TestClass]public sealed class SmartManagementPercentageProfileTests
{
 static readonly DateTime T0=new(2026,8,12,14,0,0,DateTimeKind.Utc);
 [TestMethod]public void PercentageReferences_AreSymmetric(){Assert.AreEqual(105,SmartManagementSemantics.FavorablePercentageTrigger(SmartPositionDirection.Long,100,120,25),1e-6);Assert.AreEqual(95,SmartManagementSemantics.FavorablePercentageTrigger(SmartPositionDirection.Short,100,80,25),1e-6);Assert.AreEqual(2.5,SmartManagementSemantics.PercentageStopDistance(100,90,25),1e-6);Assert.AreEqual(107.5,SmartManagementSemantics.PercentageTrailingStop(SmartPositionDirection.Long,110,100,90,25),1e-6);Assert.AreEqual(92.5,SmartManagementSemantics.PercentageTrailingStop(SmartPositionDirection.Short,90,100,110,25),1e-6);}
 [TestMethod]public void PercentageStopPlan_IsFrozen(){var s=SmartPositionEngine.Evaluate(Snap(SmartPositionDirection.Long,100,90,120),new SmartPositionSettings{EnrollRequested=true,ManagementMode=SmartManagementMode.Percentage,ConfigureStopManagementRequested=true,FinancialStopManagementEnabled=true,PreBreakEvenTrailingEnabled=true,PreBreakEvenTrailingPercentage=20,BreakEvenFinancialEnabled=true,BreakEvenTriggerPercentage=25,BreakEvenAdjustmentPercentage=10,PostBreakEvenTrailingEnabled=true,PostBreakEvenTrailingPercentage=15},null).NextState!;Assert.AreEqual(SmartManagementMode.Percentage,s.StopManagement.Mode);Assert.AreEqual(2,s.StopManagement.PreBreakEvenTrailingPriceDistance,1e-6);Assert.AreEqual(105,s.StopManagement.BreakEvenTriggerPrice!.Value,1e-6);Assert.AreEqual(1,s.StopManagement.BreakEvenAdjustmentPriceDistance,1e-6);var unchanged=SmartPositionEngine.Evaluate(Snap(SmartPositionDirection.Long,101,90,120),new SmartPositionSettings{ManagementMode=SmartManagementMode.Points},s).NextState!;Assert.AreEqual(SmartManagementMode.Percentage,unchanged.StopManagement.Mode);}
 [TestMethod]public void MultiPartial_UsesFiniteScheduleAndCurrentVolume(){var s=SmartPositionEngine.Evaluate(Snap(SmartPositionDirection.Long,100,90,120,1000),new SmartPositionSettings{EnrollRequested=true,ManagementMode=SmartManagementMode.Percentage,ConfigurePartialProfitRequested=true,FinancialPartialProfitEnabled=true,MultiPartialProfitEnabled=true,PartialProfitSpacingPercentage=20,PartialProfitClosePercent=50},null).NextState!;Assert.AreEqual(5,s.PartialProfit.MaximumStages);Assert.AreEqual(4,s.PartialProfit.StageSpacingPriceDistance,1e-6);var a=SmartPositionEngine.Evaluate(Snap(SmartPositionDirection.Long,104,90,120,1000,T0.AddSeconds(1)),new SmartPositionSettings(),s);Assert.AreEqual(1,a.Actions[0].PartialProfitStageIndex);Assert.AreEqual(500,a.Actions[0].RequestedCloseVolumeInUnits,1e-6);var accepted=SmartPositionEngine.RecordPartialProfitActionResult(a.NextState!,a.Actions[0].ActionId,SmartActionExecutionStatus.AcceptedAwaitingReconciliation);var b=SmartPositionEngine.Evaluate(Snap(SmartPositionDirection.Long,108,90,120,500,T0.AddSeconds(2)),new SmartPositionSettings(),accepted);Assert.AreEqual(1,b.NextState!.CompletedPartialProfitStageCount);Assert.AreEqual(2,b.Actions[0].PartialProfitStageIndex);Assert.AreEqual(250,b.Actions[0].RequestedCloseVolumeInUnits,1e-6);}
 [TestMethod]public void PercentageStageCount_IsFinite(){Assert.AreEqual(5,SmartManagementSemantics.PercentageMultiPartialStageCount(20));Assert.AreEqual(3,SmartManagementSemantics.PercentageMultiPartialStageCount(30));Assert.AreEqual(1,SmartManagementSemantics.PercentageMultiPartialStageCount(60));Assert.AreEqual(0,SmartManagementSemantics.PercentageMultiPartialStageCount(120));}
 [TestMethod]public void Profiles_UseSymbolAssetAccountPrecedence(){var a=Layer(SmartProfileScope.Account,7,"",30);var c=Layer(SmartProfileScope.AssetClass,7,"FX",40);var s=Layer(SmartProfileScope.Symbol,7,"EURUSD",50);var r=SmartManagementProfileResolver.Resolve(7,"FX","EURUSD",new[]{a,c,s},out var d);Assert.AreEqual(0,d.Count);Assert.AreEqual(50,r.PartialProfitClosePercent,1e-6);Assert.AreEqual(40,SmartManagementProfileResolver.Resolve(7,"FX","GBPUSD",new[]{a,c,s},out _).PartialProfitClosePercent,1e-6);Assert.AreEqual(30,SmartManagementProfileResolver.Resolve(7,"METAL","XAUUSD",new[]{a,c,s},out _).PartialProfitClosePercent,1e-6);}
 [TestMethod]public void InvalidProfile_IsIgnored(){var x=Layer(SmartProfileScope.Symbol,7,"EURUSD",50);x.SchemaVersion=999;var r=SmartManagementProfileResolver.Resolve(7,"FX","EURUSD",new[]{x},out var d);Assert.IsTrue(d.Count>0);Assert.AreEqual(50,r.PartialProfitClosePercent,1e-6);}
 static SmartManagementProfileLayer Layer(SmartProfileScope s,int a,string k,double q){var p=SmartManagementProfileResolver.BuiltInDefaults();p.PartialProfitClosePercent=q;return new SmartManagementProfileLayer{Scope=s,AccountNumber=a,ScopeKey=k,Parameters=p};}
 static SmartPositionSnapshot Snap(SmartPositionDirection d,double q,double sl,double tp,double v=1000,DateTime? t=null)=>new(){PositionId=88,SymbolName="TEST",Direction=d,EntryPrice=100,VolumeInUnits=v,StopLoss=sl,TakeProfit=tp,ObservedPrice=q,ObservedAtUtc=t??T0,IsOpen=true};
}
