using System;using System.Collections.Generic;
namespace PropRiskManager.Domain;
public enum SmartProfileScope{Account,AssetClass,Symbol}
public sealed class SmartManagementParameters{public SmartManagementMode Mode{get;set;}=SmartManagementMode.Points;public bool FinancialStopManagementEnabled{get;set;}public bool PreBreakEvenTrailingEnabled{get;set;}public bool BreakEvenEnabled{get;set;}public bool PostBreakEvenTrailingEnabled{get;set;}public double BreakEvenTrigger{get;set;}public double BreakEvenAdjustment{get;set;}public double PreBreakEvenTrailingAdjustment{get;set;}public double PostBreakEvenTrailingAdjustment{get;set;}public bool FinancialPartialProfitEnabled{get;set;}public bool MultiPartialProfitEnabled{get;set;}public double PartialProfitSpacing{get;set;}public double PartialProfitClosePercent{get;set;}}
public sealed class SmartManagementProfileLayer{public const int CurrentSchemaVersion=1;public int SchemaVersion{get;set;}=CurrentSchemaVersion;public SmartProfileScope Scope{get;set;}public int AccountNumber{get;set;}public string ScopeKey{get;set;}=string.Empty;public SmartManagementParameters Parameters{get;set;}=new();}
public static class SmartManagementProfileResolver
{
 public static SmartManagementParameters BuiltInDefaults()=>new(){Mode=SmartManagementMode.Points,BreakEvenTrigger=20,BreakEvenAdjustment=0,PreBreakEvenTrailingAdjustment=15,PostBreakEvenTrailingAdjustment=15,PartialProfitSpacing=20,PartialProfitClosePercent=50};
 public static SmartManagementParameters Resolve(int account,string? asset,string? symbol,IEnumerable<SmartManagementProfileLayer> layers,out IReadOnlyList<string> diagnostics){var r=Clone(BuiltInDefaults());var m=new List<string>();SmartManagementProfileLayer? a=null,c=null,s=null;foreach(var l in layers){if(!ValidateLayer(l,account,m))continue;if(l.Scope==SmartProfileScope.Account)a=l;else if(l.Scope==SmartProfileScope.AssetClass&&string.Equals(l.ScopeKey,asset,StringComparison.OrdinalIgnoreCase))c=l;else if(l.Scope==SmartProfileScope.Symbol&&string.Equals(l.ScopeKey,symbol,StringComparison.OrdinalIgnoreCase))s=l;}if(a!=null)r=Clone(a.Parameters);if(c!=null)r=Clone(c.Parameters);if(s!=null)r=Clone(s.Parameters);diagnostics=m;return r;}
 public static string StorageKey(SmartManagementProfileLayer l)=>l.Scope switch{SmartProfileScope.Account=>$"account:{l.AccountNumber}",SmartProfileScope.AssetClass=>$"asset:{l.AccountNumber}:{l.ScopeKey.Trim().ToUpperInvariant()}",SmartProfileScope.Symbol=>$"symbol:{l.AccountNumber}:{l.ScopeKey.Trim().ToUpperInvariant()}",_=>throw new ArgumentOutOfRangeException()};
 public static bool ValidateLayer(SmartManagementProfileLayer l,int account,ICollection<string> d){if(l.SchemaVersion!=SmartManagementProfileLayer.CurrentSchemaVersion){d.Add("Smart management profile schema is incompatible and was ignored.");return false;}if(l.AccountNumber!=account){d.Add("Smart management profile belongs to another account and was ignored.");return false;}if(l.Scope!=SmartProfileScope.Account&&string.IsNullOrWhiteSpace(l.ScopeKey)){d.Add("Smart management profile scope key is missing and was ignored.");return false;}if(!ValidateParameters(l.Parameters)){d.Add("Smart management profile contains invalid parameters and was ignored.");return false;}return true;}
 public static bool ValidateParameters(SmartManagementParameters p)=>Positive(p.BreakEvenTrigger)&&NonNegative(p.BreakEvenAdjustment)&&Positive(p.PreBreakEvenTrailingAdjustment)&&Positive(p.PostBreakEvenTrailingAdjustment)&&Positive(p.PartialProfitSpacing)&&p.PartialProfitClosePercent>0&&p.PartialProfitClosePercent<=100&&!double.IsNaN(p.PartialProfitClosePercent)&&!double.IsInfinity(p.PartialProfitClosePercent);
 private static bool Positive(double v)=>v>0&&!double.IsNaN(v)&&!double.IsInfinity(v);private static bool NonNegative(double v)=>v>=0&&!double.IsNaN(v)&&!double.IsInfinity(v);
 private static SmartManagementParameters Clone(SmartManagementParameters p)=>new(){Mode=p.Mode,FinancialStopManagementEnabled=p.FinancialStopManagementEnabled,PreBreakEvenTrailingEnabled=p.PreBreakEvenTrailingEnabled,BreakEvenEnabled=p.BreakEvenEnabled,PostBreakEvenTrailingEnabled=p.PostBreakEvenTrailingEnabled,BreakEvenTrigger=p.BreakEvenTrigger,BreakEvenAdjustment=p.BreakEvenAdjustment,PreBreakEvenTrailingAdjustment=p.PreBreakEvenTrailingAdjustment,PostBreakEvenTrailingAdjustment=p.PostBreakEvenTrailingAdjustment,FinancialPartialProfitEnabled=p.FinancialPartialProfitEnabled,MultiPartialProfitEnabled=p.MultiPartialProfitEnabled,PartialProfitSpacing=p.PartialProfitSpacing,PartialProfitClosePercent=p.PartialProfitClosePercent};
}
